### ISSUE TITLE
border methods have strange behaviour

### ISSUE THREAD

**Issue by Gargo** [YevhenBiiak/UIKitLayout#2]
```
public func border(_ edge: UIRectEdge, color: UIColor, width: CGFloat = 1) -> Self
```
This method adds subview and doesn't indicate it. What about to rename it to `createBorder` or `addBorder`?

```
public func border(_ color: UIColor, cornerRadius: CGFloat? = nil, width: CGFloat = 1) -> Self
```
if I have constant radius and width and varying color then I should specify custom width manually or call `layer.borderWidth` directly. Why not to declare `width: CGFloat? = nil` and ignore it when it is not specified.

**Comment by YevhenBiiak** [comment]
In most cases, you do not need to change the border properties (width or color). That's what these methods do. Keep It Simple Stupid! One name for a method with one overload. 

About `width: CGFloat? = nil`? Why set a border if it will not be visible?

If you want to interact with the border add it manually using the standard UIKit API

**Comment by Gargo** [comment]
@YevhenBiiak I meant a situation when you already set border width previously and need to change other border params only but ok
